version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeshare
    ports:
      - "8080:8080"
    volumes:
      - R:\HomeShare:/mnt/homeshare
    env_file:
      - api/.env.docker
    depends_on:
      - db
    networks:
      - app-network
      
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homeshare
      MYSQL_USER: homeshare_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
